### ISSUE TITLE
Regarding Emerald with patched RNG

### ISSUE THREAD

**Issue by Ephenia** [40Cakes/pokebot-bizhawk#34]
I was curious if there's support and or support could be made for Emerald that's been patched with a fix to its RNG?

Basically talking about for example the fixes that can be [found here](https://www.pokecommunity.com/showthread.php?t=217115).

The bot is really great after playing with it quite a bit, and it has definitely interested me, but it would be amazing if this could work on Emerald where its RNG is fixed and if there's a particular patch that could work with it. That's because when you are doing anything that isn't a random encounter (static) then it's really not that exciting or as satisfactory as the bot is still effectively abusing the broken RNG by doing frame perfect inputs. It would be really nice to have more consistent randomness while using the bot with Emerald.

It's fine if you wouldn't care to support this, and I still look forward to support for the other generation 3 games that of course do not have broken RNG.

Keep up the great work, though!

**Comment by 40Cakes** [comment]
What about the bot doesn't work with this RNG patch?

If you mean start resets, I would think that by using this patch then your frame IDs should be different after every reset, so the bot shouldn't wait? Or am I misunderstanding?

**Comment by 40Cakes** [comment]
Oh, do you potentially mean SR instead of running away from a legendary, out of the room and back in?

I was going to add an option to SR instead of running once Ruby and Sapphire support is added, but it'd be based on the detected game, and with this patch it will be flagged as "Emerald", but this could just be a flag in the config of course.

**Comment by Ephenia** [comment]
I think that the bot shouldn't wait is the issue using these patches, I think possibly? I did try testing a patch or 2 and I was seeing multiple PIDs in a row being the same. Sometimes 2 in a row, rarely 3, sometimes the dupes are apart from each other in-between others that are different.

I was testing starter resets mainly with it, but yeah. I would assume it wouldn't be anything else different that you do soft resets with.

**Comment by SHgligar** [comment]
> 

try this RNG fix :D ive been using this for a few days 
[MinorEm2022.zip](https://github.com/40Cakes/pokebot-bizhawk/files/11689897/MinorEm2022.zip)
it also has few added extras added like event items when unlocking mystery gifts for the 1st time and i can confirm it works witht he bot too 1 save almost 9k resets and a shiny mudkip 
![Screenshot_2023-06-03_133756](https://github.com/40Cakes/pokebot-bizhawk/assets/18070186/02557b75-7d53-4d71-a3fd-730998a06f6f)

**Comment by Ephenia** [comment]
I just tried it but I am still receiving duplicate PIDs, also running the game at 100% (normal speed) if that makes any difference?

![image](https://github.com/40Cakes/pokebot-bizhawk/assets/26987203/052f3e53-449d-4a64-b9d7-5df7965b7000)

I appreciate reaching out trying to help though. I think that it's just something that needs to be changed within the bot to properly support the patch.

**Comment by Yeenaa** [comment]
I am having the exact same issue. Patched RNG; duplicate PID pop up. **A lot.**

**Comment by SHgligar** [comment]
just so you can see if the patch is working or not id play the game (dont save) to the point you can see this in the pokemart  
![Screenshot 2023-06-09 160109](https://github.com/40Cakes/pokebot-bizhawk/assets/18070186/30be14a6-8f93-47fe-9ea6-bec7e35a69a6) 

fill in the little questionnaire

LINK TOGETHER WITH ALL
that will unlock mysterygift and it should then give you these event items
![Screenshot 2023-06-09 160407](https://github.com/40Cakes/pokebot-bizhawk/assets/18070186/6536cca4-8bd8-426a-b714-3c4317d0554e)
if the patch has worked correctly

**Comment by alexm96** [comment]
Is there a chance this is caused by a race condition? 
`emu_info["rngState"]` changing between checking and actually writing to file , hitting a, etc? 

> Interesting, because the bot uses `rngState` [here ](https://github.com/40Cakes/pokebot-bizhawk/blob/main/bot.py#L1714) to wait for a unique frame before it selects a starter and I would've thought that this patch would not return dupe states...

**Comment by NyhmsQuest** [comment]
I'm using the Pokemon Emerald National Dex Edition rom and also noticing a lot of repeat PID's.
Here is an example of 4 of the same PID.
![image](https://github.com/40Cakes/pokebot-bizhawk/assets/3873370/33bc289e-071b-495d-b117-361b0cfc69a6)
