### ISSUE TITLE
Catch extremely high IV pokemon

### ISSUE THREAD

**Issue by python-nerd-3** [40Cakes/pokebot-bizhawk#73]
If the pokemon's IV total is over 180 (or higher/lower depending on your prefrences) then the bot should try to catch it to preserve the pokemon

I find the stream very interesting, never witnessed a shiny live yet but I ocasionally come and watch it

**Comment by FlitPix** [comment]
The bot will catch a Pokemon if its IVs are all the same. ([FAQ](https://github.com/40Cakes/pokebot-bizhawk/wiki/%E2%9C%A8-Shiny-Hunting-Bot-%E2%9C%A8-Stream-FAQ#will-the-bot-catch-pok%C3%A9mon-with-perfectno-ivs--has-the-bot-seen-a-pok%C3%A9mon-with-perfectno-ivs))

As a feature I think this could be useful, but it shouldn't be the default as that takes up much more box space that ought to be used for Shinies.

**Comment by johnnieb333** [comment]
that option is already in the bot in the CustomCatchConfig  # Catch Pokémon with 4 or more max IVs in any stat
        #max_ivs = sum(1 for v in ivs if v == 31)
        #if max_ivs > 4:
        #    return True 
just change the 4 to a 3 and you will get 3 perfect IV pokemon about 4 to 5o for every shiny

**Comment by 40Cakes** [comment]
Yep, as Johnnie said, you can define your own custom catch filters in CustomCatchConfig.py in the root directory of the project. There's a few example templates commented out for you to work from.

**Comment by python-nerd-3** [comment]
sorry I tried to find it in the code and couldn't

**Comment by python-nerd-3** [comment]
I need to read more when making issues/PRs
