### ISSUE TITLE
Pokémon Home

### ISSUE THREAD

**Issue by RainerTwinkler** [40Cakes/pokebot-bizhawk#75]
Is it safe to transfer Pokémon caught with the bot to home

**Comment by pekempy** [comment]
The pokemon caught are perfectly legitimate - assuming you're using a normal ROM and not a natdex rom, so yes.
Natdex rom would have incorrect flags like met location so shouldn't be uploaded to home

**Comment by RainerTwinkler** [comment]
Thank you @pekempy
